src/Data/Record/QQ/CodeGen/HSE.hs

(required for integration RecordDotPreprocessor)

Pass TypeApplications and DataKinds extensions

---

src/Data/Record/Internal/CodeGen.hs
src/Data/Record/QQ/CodeGen.hs
src/Data/Record/QQ/Runtime/MatchHasField.hs
test/Test/Record/Sanity/Laziness.hs
test/Test/Record/Sanity/PatternMatch.hs
test/Test/Record/Sanity/QualifiedImports.hs
test/Test/Record/Util.hs

In #18 , @kana-sama rightfully points out that the current code generation for pattern matching results in types that are too polymorphic. A function such as
```haskell
foo [lr| MkT { x = a } |] = const () a
```
might get an inferred type
```haskell
foo :: forall r. HasField "x" r a => ..
```
This may lead to confusing error messages, and worse, it would make it possible to apply `foo` to an argument of a completely different record type.
#18 also adds support for empty record matches. 
The main disadvantage of #18 was that it relied on partial type signatures; requiring users to enable partial signatures in modules that use `large-records` and disable the corresponding ghc warning is a bit unfortunate. This PR supersedes #18 by resolving the problem in a slightly different way: instead …

Avoid type ambiguity, support empty patterns

---

CHANGELOG.md
large-records.cabal
src/Data/Record/Generic/Lens/VL.hs
test/Test/Record/Sanity/Lens/Micro.hs

Note that the name of the module no longer seems appropriate. I would
recommend it be changed to Data.Reocrd.Lens.
ref #26

Remove library dependency on micro-lens

---

src/Data/Record/QQ/CodeGen.hs
test/Test/Record/Sanity/PatternMatch.hs

@kana-sama pointed this problem out in #18, but I had misunderstood the point. In addition to fixing the problem in the way that #18 had already done, this now also adds a test.

Make empty pattern match strict

---

src/Data/Record/Generic.hs
src/Data/Record/TH/CodeGen.hs

We never partially apply `Constraints`, and this avoids some class aliases in user code.

Allow `Constraints` to depend on both variables

---

src/Data/Record/Generic.hs
src/Data/Record/TH/CodeGen.hs

This reverts commit a447a96954e75bfff22369a0fb0a3c8b34ed3c71.
It turns out that this does not actually help, and in fact encourages instances that result in large core size. Details in the forthcoming blog post.

Revert "Allow `Constraints` to depend on both variables"

---

large-records.cabal
test/Test/Record/Sanity/Derive.hs
test/Test/Record/Sanity/HKD.hs
test/Test/Record/Sanity/OverloadingNoDRF.hs
test/Test/Record/Sanity/QualifiedImports.hs
test/Test/Record/Sanity/RecordConstruction.hs
test/Test/Record/Size/Before/R010.hs
test/Test/Record/Size/Before/R020.hs
test/Test/Record/Size/Before/R030.hs
test/Test/Record/Size/Before/R040.hs
test/Test/Record/Size/Before/R050.hs
test/Test/Record/Size/Before/R060.hs
test/Test/Record/Size/Before/R070.hs
test/Test/Record/Size/Before/R080.hs
test/Test/Record/Size/Before/R090.hs
test/Test/Record/Size/Before/R100.hs
test/Test/Record/Size/Sanity.hs

We _always_ provide the necessary instances, but the use of the plugin (which was anyway only used within the test suite) is now optional.

Make record-dot-preprocessor optional

---

.github/workflows/haskell-ci.yml
cabal.haskell-ci
large-records/large-records.cabal
large-records/src/Data/Record/Internal/TH/Compat.hs
large-records/src/Data/Record/TH/CodeGen.hs

This is effectively #44 rebased, plus an update to CI to enable 9.0. This depends on `json-sop` version 2.1, which I just released.
Compatibility with 9.2 might be a bit trickier, since the situation with `record-dot-preprocessor` there is unclear.

Compatibility with ghc 9.0

---

.github/workflows/haskell-ci.yml
beam-large-records/CHANGELOG.md
beam-large-records/LICENSE
beam-large-records/beam-large-records.cabal
beam-large-records/src/Data/Record/Beam.hs
beam-large-records/src/Data/Record/Beam/Constraints.hs
beam-large-records/src/Data/Record/Beam/DbSettings.hs
beam-large-records/src/Data/Record/Beam/FromBackendRow.hs
beam-large-records/src/Data/Record/Beam/Internal.hs
beam-large-records/src/Data/Record/Beam/Interpretation.hs
beam-large-records/src/Data/Record/Beam/Lenses.hs
beam-large-records/src/Data/Record/Beam/Skeleton.hs
beam-large-records/src/Data/Record/Beam/ZipDatabase.hs
beam-large-records/src/Data/Record/Beam/ZipTables.hs
beam-large-records/test/Test/Record/Beam/Andres.hs
beam-large-records/test/Test/Record/Beam/SimpleSQL.hs
beam-large-records/test/Test/Record/Beam/Tutorial1.hs
beam-large-records/test/Test/Record/Beam/Tutorial2.hs
beam-large-records/test/Test/Record/Beam/Tutorial3.hs
beam-large-records/test/Test/Record/Beam/Util/Compat.hs
beam-large-records/test/Test/Record/Beam/Util/Orphans.hs
beam-large-records/test/Test/Record/Beam/Util/SQLite.hs
beam-large-records/test/Test/Record/Beam/Zipping.hs
beam-large-records/test/TestBeamLargeRecords.hs
cabal.haskell-ci
cabal.project

This moves `beam-large-records` into the larger `large-records` repo so that we can keep them in sync more easily, and updates `beam-large-records` for the latest `large-records` (without the quasi-quoter). In addition, the library itself now only depends on `large-generics`, not `large-records`.

Move beam-large-records to this repo, and update

---

large-anon/large-anon.cabal
large-anon/src/Data/Record/Anonymous/Internal.hs
large-anon/src/Data/Record/Anonymous/Plugin/Constraints/Isomorphic.hs
large-anon/src/Data/Record/Anonymous/Plugin/Constraints/RecordConstraints.hs
large-anon/src/Data/Record/Anonymous/Plugin/Constraints/RecordMetadata.hs
large-anon/src/Data/Record/Anonymous/Plugin/Record.hs
large-anon/test/Test/Record/Anonymous/Sanity/DuplicateFields.hs
large-anon/test/TestLargeAnon.hs

This wasn't correctly dealing with the fact that earlier fields shadow
later fields. This also adds some tests for duplicate fields.

Fix definition of `checkAllFieldsKnown`

---

large-anon/src/Data/Record/Anonymous.hs
large-anon/src/Data/Record/Anonymous/Internal.hs
large-anon/src/Data/Record/Anonymous/Plugin/Constraints/HasField.hs
large-anon/src/Data/Record/Anonymous/Plugin/Constraints/RecordConstraints.hs
large-anon/src/Data/Record/Anonymous/Plugin/Constraints/RecordMetadata.hs
large-anon/src/Data/Record/Anonymous/Plugin/Record.hs
large-anon/test/Test/Record/Anonymous/Sanity/Basics.hs
large-anon/test/Test/Record/Anonymous/Sanity/Casting.hs
large-anon/test/Test/Record/Anonymous/Sanity/DuplicateFields.hs
large-anon/test/Test/Record/Anonymous/Sanity/Merging.hs
large-anon/test/Test/Record/Anonymous/Sanity/Named/Record1.hs
large-anon/test/Test/Record/Anonymous/Sanity/Named/Record2.hs

DONE:
- Added functor parameter to `Record`
- Updated solvers for
* `HasField`
* `RecordConstraints`
* `RecordMetadata`
- Updated doctests 
TODO:
- Generic metadata
(we don't currently have tests for these, we should add some)
- "Simple" interface without the parameter
- API for working with this `f` parameter (mapping etc.)

Add functor parameter to `Record`

---

large-anon/large-anon.cabal
large-anon/src/Data/Record/Anonymous.hs
large-anon/src/Data/Record/Anonymous/Internal.hs
large-anon/test/Test/Record/Anonymous/Prop/Combinators/Simple.hs
large-anon/test/Test/Record/Anonymous/Prop/Model.hs
large-anon/test/Test/Record/Anonymous/Prop/Model/Generator.hs
large-anon/test/Test/Record/Anonymous/Prop/Model/Orphans.hs
large-anon/test/TestLargeAnon.hs

These are all the non-constrained combinators that we also provide for `Rep` (in `large-generics`). The constrained versions need a change to how we deal with constraints, but that in turn requires these simple combinators first, so this is step 1.
This also provides infrastructure for doing property tests over records.

Simple combinators

---

large-anon/src/Data/Record/Anonymous/Internal/Canonical.hs
large-anon/src/Data/Record/Anonymous/Internal/Diff.hs

If the `Diff` is empty, `apply` will now be `O(1)`.

Optimize `apply`

---

large-anon/large-anon.cabal
large-anon/src/Data/Record/Anon.hs
large-anon/src/Data/Record/Anon/Advanced.hs
large-anon/src/Data/Record/Anon/Plugin/Internal/Runtime.hs
large-anon/src/Data/Record/Anon/Simple.hs
large-anon/src/Data/Record/Anonymous/Advanced.hs
large-anon/src/Data/Record/Anonymous/Discovery.hs
large-anon/src/Data/Record/Anonymous/Internal/Constraints.hs
large-anon/src/Data/Record/Anonymous/Internal/Generics.hs
large-anon/src/Data/Record/Anonymous/Internal/Record.hs
large-anon/src/Data/Record/Anonymous/Internal/Reflection.hs
large-anon/src/Data/Record/Anonymous/Simple.hs
large-anon/src/Data/Record/Anonymous/TcPlugin/Constraints/Project.hs
large-anon/src/Data/Record/Anonymous/TcPlugin/Constraints/RowHasField.hs
large-anon/src/Data/Record/Anonymous/TcPlugin/NameResolution.hs
large-anon/src/Data/Record/Anonymous/TcPlugin/Solver.hs
large-anon/test/Test/Infra/Discovery.hs
large-anon/test/Test/Infra/DynRecord.hs
large-anon/test/Test/Infra/DynRecord/Advanced.hs
large-anon/test/Test/Infra/DynRecord/Simple.hs
large-anon/test/Test/Infra/MarkStrictness.hs
large-anon/test/Test/Sanity/AllFields.hs
large-anon/test/Test/Sanity/CheckCanProject.hs
large-anon/test/Test/Sanity/Discovery.hs
large-anon/test/Test/Sanity/Intersection.hs
large-anon/test/Test/Sanity/Merging.hs
large-anon/test/TestLargeAnon.hs

This makes a few changes to the `Runtime`:
- No polymorphism over proxies. Since these are internal classes anyway,
this just leads to additional complexity for benefit.
- The `RecordHasClass` no longer has a functor argument. This means that
evidence of `RecordHasClass` is now more powerful than it was before
(for _any_ `f`..).
- RecordHasClass no longer refers to any records: it just gives the
index of the field. It therefore has been renamed to `RowHasField`.
- Remove the `f` parameter from `Project` as well; this makes it
possible to define very nice `reify` and `reflect` functions for
`Project`, now entirely in line with the others. Very pretty :)

Define intersection in user-land

---

large-anon/large-anon.cabal
large-anon/src/Data/Record/Anon/Advanced.hs
large-anon/src/Data/Record/Anonymous/Advanced.hs
large-anon/src/Data/Record/Anonymous/Internal/Record.hs
large-anon/src/Data/Record/Anonymous/Simple.hs
large-anon/test/Test/Infra/DynRecord/Advanced.hs
large-anon/test/Test/Sanity/DuplicateFields.hs
large-anon/test/Test/Sanity/RecordLens.hs
large-anon/test/TestLargeAnon.hs

This makes we can more easily later add a `fieldLens` (in terms of `HasField`) if we wanted to.

Rename `lens` to `recordLens`

---

typelet/typelet.cabal

I am using typelet with stack, but found the following error.
```
Warning: typelet
has a setup-depends field, but it does not mention a Cabal dependency. This is likely to cause build errors.
typelet   > [1 of 2] Compiling Main             ( /tmp/stack-2f72c5fe4e2ab65c/typelet-0.1.1.0/Setup.hs, /tmp/stack-2f72c5fe4e2ab65c/typelet-0.1.1.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/setup/Main.o )
typelet   > [2 of 2] Compiling StackSetupShim   ( /home/jiasen/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack-2f72c5fe4e2ab65c/typelet-0.1.1.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/setup/StackSetupShim.o )
typelet   > 
typelet   > /home/jiasen/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:3:1: error:
typelet   >     Could not load module ‘Distribution.PackageDescription’ …
```

Add Cabal to setup-depends

---

large-records/src/Data/Record/Internal/GHC/Shim.hs
large-records/src/Data/Record/Internal/GHC/TemplateHaskellStyle.hs

The GHC-8.8 LPat = Pat doesn't fit the pattern anymore,
but the class is now simpler and easier to generalise for GHC-9.2,
where annotations make things a lot more complicated.

Simplify inheritLoc

---

large-anon/large-anon.cabal
large-anon/src/Data/Record/Anon/Internal/Advanced.hs
large-anon/src/Data/Record/Anon/Internal/Simple.hs
large-generics/large-generics.cabal
large-generics/src/Data/Record/Generic/NFData.hs
large-records/src/Data/Record/Plugin/Runtime.hs

Fixes #93
Added support to derive `NFData` instances generically:
Sample usage:
```haskell
import Data.Record.Plugin.Runtime (grnf)
instance NFData MyLargeRecord where
rnf = grnf
```

Derive NFData generically

---

cabal.project
large-records/large-records.cabal

This removes the temporary overrides in cabal.project.

Depend on new releases

---

.github/workflows/haskell-ci.yml
beam-large-records/beam-large-records.cabal
large-anon/CHANGELOG.md
large-anon/large-anon.cabal
large-anon/src/Data/Record/Anon/Advanced.hs
large-anon/src/Data/Record/Anon/Internal/Advanced.hs
large-anon/src/Data/Record/Anon/Internal/Core/Canonical.hs
large-anon/src/Data/Record/Anon/Internal/Core/Diff.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Constraints/AllFields.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Constraints/KnownFields.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Constraints/RowHasField.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Constraints/SubRow.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Rewriter.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Row/KnownRow.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/Row/ParsedRow.hs
large-anon/src/Data/Record/Anon/Internal/Util/StrictArray.hs
large-anon/src/Data/Record/Anon/Plugin/Internal/Runtime.hs
large-anon/test/Test/Prop/Record/Diff.hs
large-anon/test/Test/Sanity/Merging.hs
large-anon/test/Test/Sanity/Regression.hs
large-anon/test/TestLargeAnon.hs
large-generics/large-generics.cabal
large-records/large-records.cabal
typelet/typelet.cabal

This fixes #146. Most commits here are just preparatory: the actual fix is the semi-final "Reverse record order" commit. This also adds property tests that test the `Diff` operations more thoroughly (these property tests can reproduce the test case from #146 as a minimal counter-example).

Fix incremental record construction

---

large-anon/CHANGELOG.md
large-anon/large-anon.cabal
large-anon/test/Test/Sanity/Fourmolu/OverloadedRecordDot.hs
large-anon/test/Test/Sanity/Fourmolu/OverloadedRecordUpdate.hs

This extends #145 with a bit of logic to make sure the test suite still runs when the flag is used.

Disable fourmolu flag

---

large-anon/large-anon.cabal
large-generics/large-generics.cabal
large-records/large-records.cabal

So that the libraries large-anon, large-generics, and large-records compile with the current latest primitive (0.8).
This dependency bump is safe, because:
- the libraries compile after bumping primitive to >= 0.8 && < 0.9,
- the changes in primitive 0.8.0.0 do not affect the libraries:
- the changes are mostly adding new APIs and modules, and
- the only breaking change is on PrimArray, which is not used in the libraries.

Bump dependency primitive to >= 0.8 && < 0.9

---

large-records/src/Data/Record/TH.hs

I was looking for the TH from older versions of this library, and was confused about this for a moment.

Remove stale TH module

---

cabal.project

https://github.com/haskell-beam/beam/pull/585 has been merged now.

Use `beam` master 

---

.github/workflows/haskell-ci.yml
beam-large-records/beam-large-records.cabal
large-anon/large-anon.cabal
large-anon/src/Data/Record/Anon/Internal/Plugin/Source/GhcShim.hs
large-anon/src/Data/Record/Anon/Internal/Plugin/TC/GhcTcPluginAPI.hs
large-generics/large-generics.cabal
large-records-benchmarks/large-records-benchmarks.cabal
large-records/large-records.cabal
large-records/src/Data/Record/Internal/GHC/Shim.hs
large-records/src/Data/Record/Internal/GHC/TemplateHaskellStyle.hs
large-records/src/Data/Record/Internal/Plugin/CodeGen.hs
large-records/src/Data/Record/Plugin.hs
typelet/typelet.cabal

This pull request updates all libraries to be compatible with GHC 9.8. This involved updating dependencies and addressing changes in the GHC API. All tests are passing.
While the majority of the changes were straightforward, verification of two points by someone more familiar with the GHC API would be helpful:
1. **`HsTyVarBndr` and `HsBndrVis`:** GHC 9.8 introduced a `HsBndrVis` flag to `HsTyVarBndr`.  I've defaulted this to `HsBndrRequired` in  [`large-records/src/Data/Record/Internal/GHC/Shim.hs` on line 400](https://github.com/gbrsales/large-records/blob/7c47835b5169cf12200138b8708152da59eea4fc/large-records/src/Data/Record/Internal/GHC/Shim.hs#L400).  I'm unsure if this is the most appropriate default.
2. **`GHC.Types.Basic.Origin` and Pattern Matching Checks:** GHC 9.8 now requires …

Full ghc 9.8 support

---

.github/workflows/haskell-ci.yml
cabal.haskell-ci
cabal.project
large-anon/large-anon.cabal

For now this drops `-dcore-lint` from `large-anon`. I'll recover that later.

Add impl(ghc ...) conditionals to cabal.project file

---

large-anon/src/Data/Record/Anon/Plugin.hs

Having docs no user sees only confuses developers.
See #186

Remove haddock from hidden module
